addLayer("a", {
    name: "a",
    symbol: "🏆",
    position: 1,
    startData() { return {
        unlocked: true,
        points: zero,
    }},
    tooltip: "成就",
    color: "yellow",
    type: "none",
    row: "side",
    layerShown(){return true},
    achievements: {
        11:{
            name: "游戏开始",
            done(){return hasUpgrade("p",11)},
            tooltip: "购买'再回元素周期'",
            unlocked(){return true},
        },
        12:{
            name: "Machine Bug: Out of the Max.",
            done(){return player.p.filling.gt(20)},
            tooltip: "粒子收集器充能超过 20",
            unlocked(){return true},
        },
        13:{ 
            name: "夸克",
            done(){return player.p.points.gte(1)},
            tooltip: "获得 1 夸克",
            unlocked(){return true},
        },
        14:{ 
            name: "别忘记氢...",
            done(){return player.points.gte(1e10)},
            tooltip: "获得 1e10 基本粒子",
            unlocked(){return true},
        },
        15:{ 
            name: "夸克夸克夸克夸克夸克夸克",
            done(){return player.p.points.gte(6)},
            tooltip: "获得 6 夸克",
            unlocked(){return true},
        },
        16:{ 
            name: "杠杆?",
            done(){return player.p.colors[0].mul(player.p.colors[1]).mul(player.p.colors[2]).gt(0)&&player.p.colors[0].gt(player.p.colors[1].mul(10))&&player.p.colors[0].gt(player.p.colors[2].mul(10))},
            tooltip: "三个色度数量大于 0 时,红色色度比其他色度多10倍",
            unlocked(){return true},
        },
        21:{ 
            name: "平衡!",
            done(){return player.p.colors[0].mul(player.p.colors[1]).mul(player.p.colors[2]).gt(0)&&player.p.colors[0].eq(player.p.colors[1])&&player.p.colors[0].eq(player.p.colors[2])},
            tooltip: "三个色度数量大于 0 时,三色度数量相等",
            unlocked(){return true},
        },
        22:{ 
            name: "还有第二行吗?",
            done(){return hasUpgrade("p",31)},
            tooltip: "购买'保留与延拓'",
            unlocked(){return true},
        },
        23: {
            name: "Machine BBBug: Out Out of the Max.",
            done(){return player.p.filling.gt(1000)},
            tooltip: "粒子收集器充能超过 1000",
            unlocked(){return true},
        },
        24: {
            name: "Where is my boomed balloons??!!",
            done(){return player.h.points.gte(1e8)},
            tooltip: "拥有 1e8 氢",
            unlocked(){return true},
        },
        25:{ 
            name: "'氢'完了",
            done(){return hasUpgrade("h",13)},
            tooltip: "购买'遥远的目标'",
            unlocked(){return true},
        },
        26:{ 
            name: "PYROMANIA opening 9",
            done(){return player.h.hot.gt(0)},
            tooltip: "拥有超过 0 的热量",
            unlocked(){return true},
        },
        31:{ 
            name: "谁来对抗PYOROMANIA???",
            done(){return player.h.water.gt(100)},
            tooltip: "拥有超过 100 的水",
            unlocked(){return true},
        },
        32:{ 
            name: "η = W<sub>有</sub>/W<sub>总</sub>*100%",
            done(){return player.h.energy.gt(1e6)},
            tooltip: "拥有超过 1e6 的氢能",
            unlocked(){return true},
        },
        33:{ 
            name: "不要填充你的 滚木 了",
            done(){return player.h.filling[1].gt(player.h.filling[0].mul(20))},
            tooltip: "内燃机内的空气比氢气多 20 倍",
            unlocked(){return true},
        },
        34:{ 
            name: "PYROMANIA middle 12",
            done(){return player.h.hot.gt(1e12)},
            tooltip: "拥有超过 1e12 的热量",
            unlocked(){return true},
        },
        35:{ 
            name: "机械效率只有10%...但是我有倍率~",
            done(){return player.h.energy.gt(1e15)},
            tooltip: "拥有超过 1e15 的氢能",
            unlocked(){return true},
        },
        36:{ 
            name: "两个夸克如何结合成强子?",
            done(){return hasUpgrade("p",35)},
            tooltip: "购买'基础降低与效果优化'",
            unlocked(){return true},
        },
        41:{ 
            name: "你 氢 炸 了",
            done(){return player.h.points.gt(1e30)},
            tooltip: "拥有超过 1e30 的氢",
            unlocked(){return true},
        },
        42:{ 
            name: "氦 死 我 了",
            done(){return player.he.points.gte(20)},
            tooltip: "拥有 20 氦",
            unlocked(){return true},
        },
        43:{ 
            name: "PYROMANIA FINALE 14+",
            done(){return player.h.hot.gt(1e28)},
            tooltip: "拥有超过 1e28 的热量",
            unlocked(){return true},
        },
        44:{ 
            name: "不要忘记你的 pyromania",
            done(){return player.he.points.gte(40)},
            tooltip: "拥有 40 氦",
            unlocked(){return true},
        },
        45:{ 
            name: "氦-3什么情况?",
            done(){return getBuyableAmount("he","He-3").lt(tmp.he.buyables["He-3"].other)},
            tooltip: "氦-3的额外等级比基础等级还要多",
            unlocked(){return true},
        },
        46:{ 
            name: "我能造海了吗?",
            done(){return player.h.water.gt(1e40)},
            tooltip: "拥有超过 1e40 的水",
            unlocked(){return true},
        },
        51:{ 
            name: "Oh, my boomed ballooms is here.",
            done(){return hasUpgrade("he",31)},
            tooltip: "购买升级'气球之旅'",
            unlocked(){return true},
        },
        52:{
            name: "Machine Final Bug: Boomed of the Max.",
            done(){return player.p.filling.gt(1e15)},
            tooltip: "粒子收集器充能超过 1e15",
            unlocked(){return true},
        },
        53:{
            name: "PYROMANIA ENCORE 16+",
            done(){return player.h.hot.gt(1e50)},
            tooltip: "拥有超过 1e50 的热量(小趣事: 此游戏作者这个 SS)",
            unlocked(){return true},
        },
        54:{
            name: "氦气球来了",
            done(){return player.he.balloons.gte(3)},
            tooltip: "拥有 3 氦气球",
            unlocked(){return true},
        },
        55:{
            name: "氦气球又来了",
            done(){return player.he.balloons.gte(8)},
            tooltip: "拥有 8 氦气球",
            unlocked(){return true},
        },
        56:{
            name: "自动购买很好",
            done(){return player.at.running.includes("At-Ptc1")},
            tooltip: "开启自动化页面中的'自动充能'",
            unlocked(){return true},
        },
        61:{
            name: "浏览器里有一个有时间墙的小游戏",
            done(){return player.h.balloons.gte(3)},
            tooltip: "拥有 3 氢气球",
            unlocked(){return true},
        },
        62:{
            name: "怎么还有软上限/fn/fn/fn",
            done(){return layers.p.haDron("effect")[3].gte(27)},
            tooltip: "强子第四效果达到 27(注: /fn指的是qq表情中 愤怒 的表情)",
            unlocked(){return true},
        },
        63:{
            name: "禁言增量砌墙打过来了?",
            done(){return player.h.balloons.gte(8)},
            tooltip: "拥有 8 氢气球",
            unlocked(){return true},
        },
        64:{
            name: "Oh, I can boomed my He balloons then.",
            done(){return player.he.upTimes[0].gt(0)},
            tooltip: "爆炸氦气球",
            unlocked(){return true},
        },
        65:{
            name: "Oh, I can boomed my H balloons too.",
            done(){return player.he.upTimes[1].gt(0)},
            tooltip: "爆炸氢气球",
            unlocked(){return true},
        },
        66:{
            name: "操作空间有点大.",
            done(){return player.he.upTimes[0].gt(60)},
            tooltip: "爆炸氦气球效果时间超过 1 min",
            unlocked(){return true},
        },
        71:{
            name: "意味着时间墙很墙.",
            done(){return player.he.points.gte(300)},
            tooltip: "拥有 300 氦",
            unlocked(){return true},
        },
        72:{
            name: "这是 3^n 吗?",
            done(){return layers.p.haDron("num").gte(125)},
            tooltip: "解锁强子第五效果",
            unlocked(){return true},
        },
        73:{
            name: "增量之我恨时间墙.",
            done(){return player.he.points.gte(350)},
            tooltip: "拥有 350 氦",
            unlocked(){return true},
        },
        74:{
            name: "操作空间大的没边了",
            done(){return player.he.upTimes[0].gte(290)},
            tooltip: "爆炸氦气球效果时间超过 4min 50s",
            unlocked(){return true},
        },
        75:{
            name: "种子岛地质局, Lock P现场",
            done(){return player.h.hot.gt(1e100)},
            tooltip: "拥有超过 1e100 的热量",
            unlocked(){return true},
        },
        76:{
            name: "UNIFORM011",
            done(){return player.h.hot.gt(1e150)},
            tooltip: "拥有超过 1e150 的热量",
            unlocked(){return true},
        },
        81:{
            name: "时间墙还在发力",
            done(){return player.h.balloons.gte(15)},
            tooltip: "拥有 15 氢气球",
            unlocked(){return true},
        },
        82:{
            name: "这个公式是啥?",
            done(){return hasUpgrade("he",24)},
            tooltip: "购买'爆炸数量加成'",
            unlocked(){return true},
        },
        83:{
            name: "x=(x+b)/2",
            done(){return player.he.boomedNum[0].gte(18)},
            tooltip: "爆炸氦气球的爆炸平均值达到 18",
            unlocked(){return true},
        },
        84:{
            name: "x为爆炸平均值<br>b是爆炸的气球数量",
            done(){return player.he.boomedNum[1].gte(8)},
            tooltip: "爆炸氢气球的爆炸平均值达到 8",
            unlocked(){return true},
        },
        85:{
            name: "为什么一堆爆炸气球的成就?",
            done(){return player.he.balloons.gte(40)},
            tooltip: "拥有 40 氦气球",
            unlocked(){return true},
        },
        86:{
            name: "太 氢(墙) 了",
            done(){return player.h.points.gte(1e125)},
            tooltip: "拥有 1e125 氢",
            unlocked(){return true},
        },
        91:{
            name: "大墙即将来袭!!!",
            done(){return player.he.balloons.gte(41)},
            tooltip: "拥有 41 氦气球",
            unlocked(){return true},
        },
        92:{
            name: "大墙来袭,不要放弃!",
            done(){return player.he.balloons.gte(42)},
            tooltip: "拥有 42 氦气球(作者注: 43 氦气球真的墙,你可能需要在爆炸氢气球时积攒更多的氢和氢能,也可能需要一些挂机.)",
            unlocked(){return true},
        },
        93:{
            name: "大墙已过,祝你好运.",
            done(){return player.he.balloons.gte(43)},
            tooltip: "拥有 43 氦气球",
            unlocked(){return true},
        },
        94:{
            name: "我一直卡时间就为了这个时间加成/fn",
            done(){return player.a94 > 300},
            tooltip: "有在爆炸氦气球的效果持续时间 4min 30s 以上的时间超过 5min",
            unlocked(){return true},
        },
        95:{
            name: "爆炸^2 之 终于不用换着坐牢了",
            done(){return hasMilestone("he",4)},
            tooltip: "完成 '47 氦气球 & 22 氢气球' 的里程碑",
            unlocked(){return true},
        },
        96:{
            name: "Bloom in Two ENCORE 17",
            done(){return player.he.upTimes[0].mul(player.he.upTimes[1]).gt(0)},
            tooltip: "同时爆炸两种气球",
            unlocked(){return true},
        },
        101:{
            name: "成就之神I",
            done(){return player.a.achievements.length>=50},
            tooltip: "完成 50 个成就",
            unlocked(){return true},
        },
        102:{
            name: "第一周期 要结束了?",
            done(){return player.points.gte(1e175)},
            tooltip: "获得 1e175 基本粒子",
            unlocked(){return true},
        },
        103:{
            name: "通向锂最后的冲刺",
            done(){return player.points.gte(1e185)},
            tooltip: "获得 1e185 基本粒子",
            unlocked(){return true},
        },
        104:{
            name: "怎 么 还 有 墙",
            done(){return player.points.gte(1e191)},
            tooltip: "获得 1e191 基本粒子",
            unlocked(){return true},
        },
        105:{
            name: "第一周期 完结撒花!",
            done(){return player.li.points.gte(1)},
            tooltip: "获得 1 锂",
            unlocked(){return true},
        },
        106:{
            name: "我又玩了一遍第一周期(笑)",
            done(){return player.li.points.gte(2)},
            tooltip: "获得 2 锂",
            unlocked(){return true},
        },
    },
    tabFormat:{
        page1:{
            name: "第1页",
            content:[
                ["display-text",function(){return "<h2>"+quickColor("成就界面","yellow")+"</h2><br>注意事项: 本游戏的成就"+quickColor("没有","red")+"任何效果,只是用来满足一部分玩家的"+quickColor("收集癖","cyan")+",<s>以及作者的一些"+quickColor("奇怪想法","lime")+",</s>因此,成就并不一定需要都完成,"+quickColor("正常游戏过程","blue")+"中也不需要完成所有成就,它只是"+quickColor("游戏进度","orange")+"的一种指示."}],
                "blank",
                ["achievements",[1,2,3,4]],
            ],
            unlocked(){return true},
            buttonStyle: {
                "border-color": "cyan"
            },
        },
        page2:{
            name: "第2页",
            content:[
                ["achievements",[5,6,7,8,9,10]],
            ],
            unlocked(){return player.h.unlocked},
            buttonStyle: {
                "border-color": "#EEEEEE"
            },
        },
        page3:{
            name: "第3页",
            content:[
                ["achievements",[11,12,13,14,15,16]],
            ],
            unlocked(){return player.li.unlocked},
            buttonStyle: {
                "border-color": "#f05c82"
            },
        },
    },
})